Refine cells taking into account width, length, height
OPM/opm-grid pull request #715
Opened 2024-03-12 16:47 UTC by aritorto

A new method has been added in Geometry, to refine a single cell taking into account different widths, lengths, and heights.  It generalizes the previous refine() whose refinement is uniform. 

The code incorporated can be shortened, for example, when computing the variations on x-axis, y-axis, z-axis. Those details are postponed.

2024-03-12 16:47 UTC, aritorto commented
jenkins build this please

2024-03-13 08:12 UTC, blattms requested changes
Just some comments. Printing should be removed before merging.

2024-03-13 08:12 UTC, blattms commented on opm/grid/cpgrid/Geometry.hpp
> +                            const double local_z = localCoordNumerator(dz, k/cells_per_dim[2], double((k % cells_per_dim[2])) /cells_per_dim[2]);
This looks really complicated. It took me a long time to understand it. That might be me, of course. I would probably have done it like this (just keeping track of the coordinates by adding to them):
```suggestion
                double local_y = 0;
                for (int j = 0; j < refined_dim[1] +1; ++j, local_y+=dy[j]) {
                    double local_x = 0;
                    for (int i = 0; i < refined_dim[0] +1; ++i, local_x+=dx[i]) {
                        double local_z = 0;
                        for (int k = 0; k < refined_dim[2] +1; ++k, local_z+=dz[k]) {
                            // Compute the index of each global refined corner associated with 'jik'.
                            int refined_corner_idx =
                                (j*(refined_dim[0]+1)*(refined_dim[2]+1)) + (i*(refined_dim[2]+1)) + k;
                            // local_x, local_y, and local z should already be correct now.
```

2024-03-14 09:33 UTC, aritorto commented on opm/grid/cpgrid/CpGridData.hpp
> +
Yes, that makes sense. Thanks!

2024-03-14 09:34 UTC, aritorto commented on opm/grid/cpgrid/Geometry.hpp
> +                            assert(local_x/sum_dx <= 1.);
Shall I remove these asserts? Or add certain tolerance? For example, 1. + e-6 ?

2024-03-14 09:55 UTC, aritorto commented on opm/grid/cpgrid/CpGridData.cpp
> +                       ((aFewCorners[1][2] -aFewCorners[0][2])*(aFewCorners[1][2] -aFewCorners[0][2])));
Thanks! it's changed now

2024-03-14 09:55 UTC, aritorto commented
jenkins build this please

2024-03-19 16:55 UTC, merged